### ISSUE TITLE
Add twitter handle to customized profile

### ISSUE THREAD

**Issue by rukundob451** [Tess314/Tess314#1]
- add twitter handle to customized profile

**Comment by Tess314** [comment]
Have added Twitter handle to profile

**Comment by rukundob451** [comment]
Glad you were able to add it mate

**Comment by Tess314** [comment]
> Glad you were able to add it mate

Thanks for helping out! Good you're practicing.

**Comment by rukundob451** [comment]
Yeah, trying my best to get good at it.
